version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  app:
    image: devinpeace/radii-app:latest
    depends_on:
      - "db"
    links:
      - "db"
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql+psycopg2://postgres@db:5432/radii_app
    command: bash -c "./scripts/wait-for.sh db:5432 -- flask db migrate && flask db upgrade && gunicorn app:app --bind 0.0.0.0:3000 --workers=2 --worker-class="egg:meinheld#gunicorn_worker""