version: '3.2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    image: devinpeace/radii-app:latest
    depends_on:
      - "db"
    links:
      - "db"
    ports:
      - "3000:8000"
    environment:
      - HOST=0.0.0.0
    command: bash -c "./scripts/wait-for.sh db:3306 -- flask db upgrade && gunicorn app:app --bind 0.0.0.0:8000 --workers=2 --worker-class="egg:meinheld#gunicorn_worker""