version: '3'
services:
  app:
    image: devinpeace/radii-app:latest
    links: 
      - db
    ports:
      - "80:80"
    environment:
      - HOST=0.0.0.0
    command: bash -c "flask db upgrade && gunicorn app:app --bind 0.0.0.0:80"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro  