version: '3'
services:
  app:
    image: devinpeace/radii-app:latest
    depends_on:
      - db
    links: 
      - db
    ports:
      - "80:8080"
    environment:
      - HOST=0.0.0.0
    command: bash -c "flask db migrate && flask db upgrade && gunicorn app:app --bind 0.0.0.0:8080 --workers=2 --worker-class="egg:meinheld#gunicorn_worker""
      
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro  