version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: radii_app
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data

  app:
    image: devinpeace/radii-app:latest
    depends_on:
      - "db"
    links:
      - "db"
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql+psycopg2://postgres@db:5432/radii_app
      - FLASK_APP=app.py
      - SERVER_NAME=radii.devinpeace.com
    command: bash -c "./scripts/wait-for.sh db:5432 -- cp -a ./migration-data/migrations ./ && flask db migrate && flask db upgrade && gunicorn app:app --bind 0.0.0.0:3000 --workers=2 --worker-class="egg:meinheld#gunicorn_worker""
    volumes:
      - ./migration-data:/radii/migration-data