version: '3'
services:
  app:
    image: devinpeace/radii-app:latest
    depends_on:
      - db
    links: 
      - db
    ports:
      - "443:443"
    environment:
      - HOST=0.0.0.0
    command: bash -c "cat app/static/styles/main.css && flask db migrate && flask db upgrade && gunicorn app:app --certfile=$CERT_FILE --keyfile=$KEY_FILE --bind 0.0.0.0:443 --workers=2 --worker-class="egg:meinheld#gunicorn_worker""
      
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro  