version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup venv and installing dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest -p no:warnings

  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup venv and installing dependencies
          command: |
            echo 'export IMAGE_NAME=radii-app' >> $BASH_ENV
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            ./scripts/pack.sh

  deploy:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to GCP
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  